title: Vinson's website
baseURL: /
params:
  googleAnalyticsID: G-4NGBF2S8VM
  layout_style: overflow
  palette: green
  color: 
    Python : #306998
    Julia : #9558B2
    Statistics : #c90e0e
    Optimization : #3ddbce
  header:
    title: Vinson Ciawandy
    tagline: Data Science | Analytics | Mathematics
    profile_img: images/image (1).png
    profile_img_alt: Author avatar
    background: dark
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Search tags
        url: /tags
        style: link
        icon_class: dev
        new_window: false
        no_follow: false
        type: action
      - label: Posts
        url: /blog/
        style: link
      - label: About Me
        url: /about/
        style: link
      - label: Contact
        url: /contact/
        style: link
    has_social: true
    social_links:
      - label: GitHub
        url: 'http://github.com/vinson2233/'
        style: icon
        icon_class: github
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/in/vinsonciawandy/'
        style: icon
        icon_class: linkedin
        new_window: true
  footer:
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=fresh&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
  domain: 'https://vinson2233.netlify.app'
  favicon: images/favicon01.png
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
